# Generated by Django 4.1.7 on 2023-06-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_app', '0002_employee_hire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dep',
            new_name='department',
        ),
    ]
